export const CREATE_RESTAURANTS_REQUEST = "CREATE_RESTAURANTS_REQUEST";
export const CREATE_RESTAURANTS_SUCCESS = "CREATE_RESTAURANTS_SUCCESS";
export const CREATE_RESTAURANTS_FAITURE = "CREATE_RESTAURANTS_FAITURE";

export const GET_ALL_RESTAURANTS_REQUEST = "GET_ALL_RESTAURANTS_REQUEST";
export const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS";
export const GET_ALL_RESTAURANTS_FAITURE = "GET_ALL_RESTAURANTS_FAITURE";

export const DELETE_RESTAURANTS_REQUEST = "DELETE_RESTAURANTS_REQUEST";
export const DELETE_RESTAURANTS_SUCCESS = "DELETE_RESTAURANTS_SUCCESS";
export const DELETE_RESTAURANTS_FAITURE = "DELETE_RESTAURANTS_FAITURE";

export const UPDATE_RESTAURANTS_REQUEST = "UPDATE_RESTAURANTS_REQUEST";
export const UPDATE_RESTAURANTS_SUCCESS = "UPDATE_RESTAURANTS_SUCCESS";
export const UPDATE_RESTAURANTS_FAITURE = "UPDATE_RESTAURANTS_FAITURE";

export const GET_RESTAURANTS_BY_ID_REQUEST = "GET_RESTAURANTS_BY_ID_REQUEST";
export const GET_RESTAURANTS_BY_ID_SUCCESS = "GET_RESTAURANTS_BY_ID_SUCCESS";
export const GET_RESTAURANTS_BY_ID_FAITURE = "GET_RESTAURANTS_BY_ID_FAITURE";

export const GET_RESTAURANTS_BY_USER_ID_REQUEST = "GET_RESTAURANTS_BY_USER_ID_REQUEST";
export const GET_RESTAURANTS_BY_USER_ID_SUCCESS = "GET_RESTAURANTS_BY_USER_ID_SUCCESS";
export const GET_RESTAURANTS_BY_USER_ID_FAITURE = "GET_RESTAURANTS_BY_USER_ID_FAITURE";

export const UPDATE_RESTAURANTS_STATUS_REQUEST = "UPDATE_RESTAURANTS_STATUS_REQUEST";
export const UPDATE_RESTAURANTS_STATUS_SUCCESS = "UPDATE_RESTAURANTS_STATUS_SUCCESS";
export const UPDATE_RESTAURANTS_STATUS_FAITURE = "UPDATE_RESTAURANTS_STATUS_FAITURE";

export const CREATE_EVENTS_REQUEST = "CREATE_EVENTS_REQUEST";
export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
export const CREATE_EVENTS_FAITURE = "CREATE_EVENTS_FAITURE";

export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAITURE = "GET_ALL_EVENTS_FAITURE";

export const DELETE_EVENTS_REQUEST = "DELETE_EVENTS_REQUEST";
export const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS";
export const DELETE_EVENTS_FAITURE = "DELETE_EVENTS_FAITURE";

export const GET_RESTAURANTS_EVENTS_REQUEST = "GET_RESTAURANTS_EVENTS_REQUEST";
export const GET_RESTAURANTS_EVENTS_SUCCESS = "GET_RESTAURANTS_EVENTS_SUCCESS";
export const GET_RESTAURANTS_EVENTS_FAITURE = "GET_RESTAURANTS_EVENTS_FAITURE";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAITURE = "CREATE_CATEGORY_FAITURE";

export const GET_RESTAURANTS_CATEGORY_REQUEST = "GET_RESTAURANTS_CATEGORY_REQUEST";
export const GET_RESTAURANTS_CATEGORY_SUCCESS = "GET_RESTAURANTS_CATEGORY_SUCCESS";
export const GET_RESTAURANTS_CATEGORY_FAITURE = "GET_RESTAURANTS_CATEGORY_FAITURE";



